plugins:
  events_enabled:
    default: false
    client: true
  events_agenda_enabled:
    default: false
    client: true
  events_calendar_enabled:
    default: false
    client: true
  events_add_to_calendar:
    client: true
    default: false
  events_event_label_icon:
    client: true
    default: 'calendar'
  events_event_label_no_text:
    client: true
    default: false
  events_event_label_format:
    client: true
    default: 'MMMM Do, HH:mm'
  events_event_label_short_format:
    client: true
    default: 'M-D, HH:mm'
  events_event_label_short_only_start:
    client: true
    default: false
  events_event_label_short_after_title:
    client: true
    default: false
  events_event_time_calendar_format:
    client: true
    default: 'HH:mm'
  events_remove_past_from_agenda:
    default: false
  events_remove_past_from_map:
    default: false
  events_remove_past_from_calendar:
    default: false
  events_agenda_filter_closed:
    default: false
  events_calendar_filter_closed:
    default: false
  events_timezone_default:
    default: ''
    client: true
    enum: 'EventsTimezoneDefaultSiteSetting'
  events_timezone_display:
    client: true
    default: 'default'
    enum: "EventsTimezoneDisplaySiteSetting"
  events_timezone_include_in_topic:
    default: true
    client: true
  events_timezone_include_in_topic_list:
    default: true
    client: true
  events_timezone_include_in_email:
    default: true
  events_timezone_format:
    default: ''
    client: true
  events_timezone_rails_format:
    default: true
    client: true
  events_hamburger_menu_calendar_link:
    default: false
    client: true
  events_hamburger_menu_agenda_link:
    default: false
    client: true
  events_min_trust_to_create:
    default: 0
  events_rsvp:
    default: false
    client: true
  events_webcal_always_add_user_api_key:
    default: false
    client: true
